version: "3.1"
services:
  php7:
    build:
      context: docker/apache_php
    container_name: yii_2_php
    links:
      - db
      - phpmyadmin
    ports:
      - "82:80"
    volumes:
      - .:/var/www/project
      - ~/.composer/auth.json:/root/.composer/auth.json

  db:
    build:
      context: docker/db
    container_name: yii_2_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=yii_2
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "3308:3306"
  phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      ports:
        - "8082:80"